const addresses = [
  "1500 Sutter St San Francisco, CA",
  "420 Precita Ave San Francisco, CA",
  "430 Lily St San Francisco, CA",
  "33 Shields St San Francisco, CA",
  "354 Eddy St San Francisco, CA",
  "36 Cragmont Ave San Francisco, CA",
  "216 Eddy St San Francisco, CA",
  "794 Mcallister St San Francisco, CA",
  "66 Ceres St San Francisco, CA",
  "68 Dakota St San Francisco, CA",
  "725 Green St San Francisco, CA",
  "762 Fulton St San Francisco, CA",
  "766 Sutter St San Francisco, CA",
  "209 Blythedale Ave San Francisco, CA",
  "5821 Geary Blvd San Francisco, CA",
  "1366 33rd Ave San Francisco, CA",
  "4545 Anza St San Francisco, CA",
  "1405 Gough St San Francisco, CA",
  "211 23rd Ave San Francisco, CA",
  "411 Hayes St San Francisco, CA",
  "1775 Fulton St San Francisco, CA",
  "1650 Page St San Francisco, CA",
  "607 Divisadero St San Francisco, CA",
  "28 6th St San Francisco, CA",
  "3038 Fulton St San Francisco, CA",
  "3199 Clement St San Francisco, CA",
  "5230 Fulton St San Francisco, CA",
  "672 Geary St San Francisco, CA",
  "3355 Geary Blvd San Francisco, CA",
  "1802 Balboa St San Francisco, CA",
  "1691 Oakdale Ave San Francisco, CA",
  "850 La Playa St San Francisco, CA",
  "798 Arguello Blvd San Francisco, CA",
  "794 Mcallister St San Francisco, CA",
  "66 Ceres St San Francisco, CA",
  "652 Polk St San Francisco, CA",
  "68 Dakota St San Francisco, CA",
  "4052 Balboa St San Francisco, CA",
  "563 Ruger St San Francisco, CA",
  "725 Green St San Francisco, CA",
  "762 Fulton St San Francisco, CA",
  "354 Eddy St San Francisco, CA",
  "1535 Pacific Ave San Francisco, CA",
  "1222 Harrison St San Francisco, CA",
  "560 Divisadero St San Francisco, CA",
];

const phoneNumbers = [
    '4156545654',
    '4156982314',
    '4156549466',
    '4156454813',
    '4159746464',
    '4155464646',
    '4153458786',
    '4155897478',
    '4156554684',
    '4153646542',
    '4158879895',
    '4155544223',
    '4156549846',
    '4155458796',
    '4150818181',
    '4151949846',
    '4156598484',
    '4159498498',
    '4153533757',
    '4152498464',
    '4156545646',
    '4156461531',
    '4156549844',
    '4156548946',
    '4156498415',
    '4156573421',
    '4153618745',
    '4153579846',
    '4155491642',
    '4153549813',
    '4155491351',
]

const firstNames = [
    "Adrian",
    "Walker",
    "Vanessa",
    "Joe",
    "Aatef",
    "Adam",
    "Ahmed",
    "Albert",
    "Alex",
    "Alexander",
    "Anya",
    "Ayce",
    "Camille",
    "Clint",
    "Daniel",
    "Elijah",
    "Henry",
    "Israel",
    "Jack",
    "Jacob",
    "Mike",
    "Michelle",
    "Jen",
    "Jaron",
    "Jordan",
    "Kenneth",
    "Kevin",
    "Kodi",
    "Leah",
    "Maggie",
    "Nate",
    "Nick",
    "Nyki",
    "Philip",
    "Phil",
    "Reed",
    "Sean",
    "Shanelle",
    "Solomon",
    "Suliz",
    "Thomas",
    "Tim",
    "Charlotte",
    "Will",
    "Winfred",
    "Xiao",
    "Emily",

]

const lastNames = [
 "Baransy",
 "Klimmek",
 "Apodaca",
 "El Mahallawy",
 "Chen",
 "Choy",
 "Mak",
 "Anya",
 "Lecap",
 "Fogg",
 "Chu",
 "Gu",
 "Dove",
 "Han",
 "Gonzalez",
 "Fragassi",
 "Prall",
 "Lee",
 "Phan",
 "Guan",
 "Besenio",
 "Ross",
 "Zhang",
 "Shiflett",
 "De La Pena",
 "Yao",
 "Gallagher",
 "Sercel",
 "Wiehe",
 "Tynan",
 "Gresham",
 "Haubenstock",
 "Scott",
 "Valencia",
 "Dove",
 "Basnet",
 "Grega",
 "Harding",
 "Sun",
 "Offit",
 "Huang",
 "Yu",
 "Chen"
]

const details = [
    "I have a lot of boxes. I need some help moving them.",
    "Partner kicked me out for buying roses on amazon.",
    "Can you help me get this stuff out of here? Much obliged!",
    "I've gotta move my goldfish. She needs a calm driver",
    "Please help me move all of this sand.",
    "This shouldn't take too long.",
    "Don't look in my boxes!",
    "I've got a lot of old records. Mostly billy joel. All being driven to the dump.",
    "Fiesta-ware needs to be dropped off at my mom's.",
    "I have a bunch of empty boxes, but I'm not sure what size car I need",
    "Ogan delivery. Must be quick!",
    "I'm taking the plumbing from my old apartment to my new one.",
    "Need help with all of my illusions. Taking them to a warehouse.",
    "I have a few garbage bags full of spare change that I need help with.",
    "Small move. Just some clay in tupperware.",
    "I'm delivering vacuum cleaners!",
    "Old cables and such.",
    "If the boxes growl it's...just a recording.",
    "I have a couple buckets full of rusty nails that I'm dropping off with my grandma.",
    "Salesforce swag. So much salesforce swag.",
    "hand delivering kettle-bells to a kindergarten",
    "I've dismantled my refrigerator and oven. Need help moving them to a place where I'll fuse them.",
    "My cats are kicking me out. Lots of furniture.",
    "Delivering guitars to my friend Reggie.",
    "Several burlap sacks full of broken glass. Don't ask questions.",
    "Help me move a couple cases of bubblegum. I'll give you one as a tip.",
    "Expired cabbage. I've got to get it out of here.",
    "Help me haul my stepdad...someplace else.",
    "there's a shiny nickle in it for ya if you help me move this baby grand piano.",

]





module.exports = {
    addresses,
    phoneNumbers,
    firstNames,
    lastNames,
    details
}